version: latest

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: ['sh', '-c', 'npx prisma db push && npx prisma generate && npx nx run app:serve']
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - 4200:4200

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


volumes:
  mono-node-modules: null