version: latest

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: yarn nx run app:serve
    ports:
      - 4200:4200

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


volumes:
  mono-node-modules: null